\literate[Ppgen]
% GT -- Grammar Tools
% Copyright (C) 2000 Merijn de Jonge <mdejonge@cwi.nl>
%                    Eelco Visser <visser@acm.org>
%                    Joost Visser <jvisser@cwi.nl>
%
% This program is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2, or (at your option)
% any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
% 02111-1307, USA.

% $Id: Ppgen.r,v 1.4 2001/09/01 20:44:11 mdejonge Exp $

% Author: Merijn de Jonge (mdjonge@cwi.nl)

\begin{code}
module Ppgen
imports make pp-tables-io asfix lib misc Label-Sdf-Syntax Basic-Sdf-Syntax 
        Bracket-Symbol

strategies
Ppgen = iowrap( (id, ppgenerate),
                Option( "-v", !Verbose()),
                usage' )

\end{code} 

   A pretty-print table is generated by collecting all context-free
   prodcutions from an sdf module or definition and generating BOX templates
   for each production and, recursively for each nested symbol of the
   production.

\begin{code}
  ppgenerate = 
  // Obtain all context-free productions 
     collect'( \ context-free-syntax(productions) -> productions \ )
  ;  concat

  // De-quote all strings
  ;  topdown(try( \ cons(s) -> cons(<de-quote>s) \
                + \ lit(s)  -> lit(<de-quote>s) \
                + \ sort(s) -> sort(<de-quote>s) \
                ))
   
   // Create BOX templates for each production
   ; map(generate-pp-entries)
   ; filter( not(?[]) )
   ; concat => pp-entries

   // Construct a valid AST for the pretty-print table
   ; !PP-Table(pp-entries)
   ; topdown(try( \Arg(n) -> Arg(<int-to-string>n) \
                + \selector( n, x ) -> selector(<int-to-string>n, x) \
                + \S(s) -> S(<quote>s) \
                ))
\end{code}
