# generic rules
%.runtestsuite : %.atestsuite
	$(SDF_TOOLS)/bin/parse-unit -i $< -p $(PARSE_UNIT_PTABLE) --verbose 1 -o /dev/null

%.atestsuite : %.testsuite
	$(SDF_TOOLS)/bin/parse-parse-testsuite  -i $< -o $@
