# generic rules
PARSE_UNIT=XTC_REPOSITORY="$(BUILD_REPOSITORY)" $(top_builddir)/../sdf-tools/analyse/parse-unit/parse-unit

%.runtestsuite : %.testsuite
	$(PARSE_UNIT) -i $< -p $(PARSE_UNIT_PTABLE)

check: $(TESTSUITES:.testsuite=.runtestsuite)
