ATerm SSL_is_int(ATerm) ;
ATerm SSL_addi(ATerm, ATerm) ;
ATerm SSL_addr(ATerm, ATerm) ;
ATerm SSL_subti(ATerm, ATerm) ;
ATerm SSL_subtr(ATerm, ATerm) ;
ATerm SSL_muli(ATerm, ATerm) ;
ATerm SSL_mulr(ATerm, ATerm) ;
ATerm SSL_divi(ATerm, ATerm) ;
ATerm SSL_divr(ATerm, ATerm) ;
ATerm SSL_mod(ATerm, ATerm) ;
ATerm SSL_lti(ATerm, ATerm) ;
ATerm SSL_gti(ATerm, ATerm) ;
ATerm SSL_gtr(ATerm, ATerm) ;
ATerm SSL_int(ATerm) ;
ATerm SSL_srand(ATerm) ;
ATerm SSL_RAND_MAX() ;
ATerm SSL_rand() ;
ATerm SSL_int_to_string(ATerm) ;
ATerm SSL_string_to_int(ATerm) ;
