#!/bin/bash
#
# by Lennart Kats <lennart add lclnet.nl>

IOPTION=
FOPTION=
COPTION=
MOPTION=
GOPTION=
LOPTION=
LAOPTION=
INPUTFILE=
OOPTION="-O 1"

while true; do
  if [ "$1" = "-c" ] || [ "$1" == "--indent-c" ]; then
    COPTION="-c --indent-c"
    shift
    continue
  fi

  if [ "$1" = "-F" ]; then
    FOPTION="-F"
    shift
    continue
  fi
  
  if [ "$1" = "--library" ] || [ "$1" = "--lib" ]; then
    LOPTION="--library"
    shift
    continue
  fi
  
  if [ "$1" = "-g" ]; then
    GOPTION="-g"
    shift
    continue
  fi
  
  if [ "$1" = "-m" ]; then
    MOPTION="-m $2"
    shift; shift
    continue
  fi
  
  if [ "$1" = "-O" ]; then
    OOPTION="-O $2"
    shift; shift
    continue
  fi
  
  if [ "$1" = "-la" ]; then
    LAOPTION="$LAOPTION -la $2"
    shift; shift
    continue
  fi
  
  if [ "$1" = "-I" ]; then
    IOPTION="-I $2"
    shift; shift
    continue
  fi
  
  if [ "$1" = "-i" ]; then
    INPUTFILE=$2
    shift; shift
    continue
  fi
  
  if (echo "$1" | grep -e '^ [^ ]\.' &>/dev/null || [ -f "$1" ]) && [ $# = 1 ]; then
    if [ -f "$1" ]; then
      INPUTFILE=$1
    else
      echo Not a Stratego module: $1 >&2
      exit 1
    fi
  fi
  
  if [ "$1" = "--help" ] || [ "$1" = "-h" ] ||
     ([ $# = 0 ] && [ "$INPUTFILE" = "" ]) ||
     echo "$1" | grep '^-' &>/dev/null; then
    echo 'Usage: str [-c | -F | -g] [OPTIONS] [-i FILE | INPUT]'
    echo 'Compile and run Stratego program in FILE or from INPUT.'
    echo
    echo 'COMMANDS:'
    echo '  -c        Display program output C code instead of running it.'
    echo '  -F        Display program in core format instead of running it.'
    echo '  -g        Run program using gdb and display backtrace.'
    echo
    echo 'OPTIONS:'
    echo '  --lib     Treat as library, keeping all unused strategies.'
    echo '  -la NAME  Search the libtool library libNAME.la when linking.'
    echo '  -m NAME   Sets the main strategy to use (default main).'
    echo '  -I DIR    Include modules from directory DIR.'
    echo '  -O N      Use optimization level N (default 1).'
    echo
    echo 'INPUT:'
    echo '  -i FILE   Read input from FILE.'
    echo '  INPUT     Use INPUT as the input program (typically specified using single quotes).'
    echo '            Can be a single strategy or a complete module'
    exit
  fi
  break
done

if [ "$TEMP" == "" ]; then
  TEMP=/tmp
fi
TEMPFILE=$TEMP/str-`date +'%N'`.str
[ -d $TEMP/.libs ] || (mkdir $TEMP/.libs; chmod 777 $TEMP/.libs)
  
if [ "$INPUTFILE" == "" ]; then
  if echo "$@" | grep '^module ' >/dev/null; then
    PROGRAM="$@"
  else
    PROGRAM="module foo imports libstratego-lib libstratego-xtc libstratego-sglr libstratego-rtg libstrc rules main =
$@"
  fi
  echo "$PROGRAM" |
    perl -pe 's/\blibstratego-lib\b//; s/module\s+[\w\-'']+\b/$& imports libstratego-lib strategies/' > $TEMPFILE
  INPUTFILE=$TEMPFILE
fi

(strc $FOPTION $LOPTION $COPTION $MOPTION $OOPTION $IOPTION $LAOPTION --format-check 0 -Xcc -O0 -la stratego-lib -la stratego-xtc -la strc -la stratego-sglr -la stratego-rtg -I . -i $INPUTFILE -o $TEMPFILE.out --statistics 0 || exit 1) 2>&1 | grep -vE '^ *[ig]cc|warning ] Mismatch between basename|info ] Compiling|libtool: '
RET=$?

rm -f $TEMPFILE

if [ -e $TEMPFILE.out ]; then
  if [ $FOPTION ]; then
    (pp-stratego -a -i $TEMPFILE.out || pp-aterm -i $TEMPFILE.out)
  elif [ $GOPTION ]; then
    echo 'run
          backtrace' > $TEMPFILE.gdb
    gdb -batch -x $TEMPFILE.gdb $TEMPFILE.out
    RET=$?
  else
    $TEMPFILE.out
    RET=$?
  fi
elif [ "$COPTION" ]; then
  cat $TEMPFILE.c
fi

rm -f $TEMPFILE.out $TEMPFILE.gdb $TEMPFILE.c \
      $TEMPFILE.str.lo $TEMPFILE.str.la $TEMPFILE.str.out.dep $TEMPFILE.str.c

exit $RET
