#! /bin/sh -e

# Environment variables for our Gentoo friends.
export WANT_AUTOMAKE="1.8"
export WANT_AUTOCONF="2.59"

# Determine autoxt to use.
if test -z "$STRATEGOXT_BASELINE"; then
  echo "***********************************************************"
  echo "                          WARNING"
  echo ""
  echo "The environment variable STRATEGOXT_BASELINE is not set."
  echo "It is recommended to set this variable to make sure that"
  echo "the right autoxt is used for bootstrapping Stratego/XT. I"
  echo "assume that the baseline you want to use is on the path."
  echo "***********************************************************"
  AUTOXT="autoxt"
elif test !-x "$STRATEGOXT_BASELINE/bin/autoxt"; then
  echo "error: $STRATEGOXT_BASELINE/bin/autoxt does not exist."
  echo "Please check your STRATEGOXT_BASELINE environment variable"
  exit 1
elif test -x "$STRATEGOXT_BASELINE/bin/autoxt"; then
  AUTOXT="$STRATEGOXT_BASELINE/bin/autoxt"
else
  echo "This is impossible in theory and practice."
  exit 1
fi

echo "bootstrap: using autoxt at $AUTOXT"

# Apply the autotools
$AUTOXT
cp ./autoxt.m4 ./config/
autoreconf -ifv

# Bootstrap the subpackages
PKGS="autoxt srts xtc xtc2 xtc3 strc ssl gpp c-tools concrete-syntax \
  aterm-front stratego-front asfix-tools sdf-front sdf-tools \
  stratego-regular xml-front xtar boxenv stratego-lib strc-core"

for dir in $PKGS
do 
  echo
  echo "bootstrap: bootstrapping in $dir"
  echo
  cd $dir
  if test "$dir" != "autoxt"
  then
    cp ../Makefile.xt .
  fi
  autoreconf -ifv
  cd ..
done
