#! /bin/sh
#
# autobundle -- Make distributions by bundling separate software packages.
#
# Copyright (C) 2000 Merijn de Jonge <mdejonge@cwi.nl>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.

# $Id: bootstrap,v 1.4 2002/11/23 11:30:45 stratego Exp $

rm -f mkinstalldirs missing install-sh

PKGS="srts sc-boot boxenv gpp-boot cgen ssl aterm-tools asfix-tools graph-tools gpp sdf-tools stratego-tools stratego-front sc xt boxenv"

#gbtools stratego-connect grammar-recovery 

for dir in $PKGS
do 
  echo
  echo "reconfiguring in $dir"
  echo
  (cd $dir; sh ./bootstrap)
done

rm -f config.cache
rm -f acconfig.h
aclocal
autoconf
#acconfig
autoheader
automake -a


