#! /bin/sh

./bootstrap
./configure --prefix=/usr/local/build/Boot \
    --with-aterm=/usr/local/build/ATerm \
    --with-sdf=/usr/local/build/SDF2 \
    --with-stratego-xt=/usr/local/build/Boot \
    --with-repository=/usr/local/build/Boot/share/StrategoXT/XTC

exit 0

./bootstrap
./configure \
    --prefix=/home/xt/XT \
    --with-aterm=/home/xt/XT \
    --with-sc-boot=`pwd`/../sc-boot \
    --with-rpmdir=/home/visser/rpm

exit 0

./reconf
./configure \
    --prefix=/home/xt/xt \
    --with-aterm=/home/xt/ATerm \
    --with-sc-boot=`pwd`/../sc-boot \
    --with-rpmdir=/home/visser/rpm

exit 0

echo "this should'nt be executed"

    --with-gpp=/home/xt/xt \

./configure --prefix=`pwd`/../sc-boot \
	--with-aterm=`pwd`/../aterm \
	--with-cgen=`pwd`/../cgen \
	--with-gpp=`pwd`/../gpp-boot \
	--with-boot=`pwd`/../sc-boot \
	--with-sc-boot=`pwd`/../sc-boot \
	--with-ssl=`pwd`/../ssl \
	--with-srts=`pwd`/../srts 

#	--with-stratego-boot=`pwd` \
#	--with-stratego-boot=/home/xt/xt \
#	--with-stratego-boot=`pwd`/../stratego-boot \

#	--with-cpl=/home/visser/res/sandbox/cpl \

./bootstrap
./configure --prefix=`pwd`/.. \
    --with-rpmdir=/home/visser/rpm
