include /home/xt/XT/share/srts/Makefile.srts

SUFFIXES = .str .cr

SCOMPILE = /home/xt/XT/bin/sc

.rtree.c : 
	$(SCOMPILE) $(STRINCLUDES) $(SCFLAGS) -i $< -o $@ -c

.str.c : 
	$(SCOMPILE) $(STRINCLUDES) $(SCFLAGS) -i $< -o $@ -c

.cr.c : 
	$(SCOMPILE) $(STRINCLUDES) $(SCFLAGS) -i $< -o $@ -c

%.c.dep : 
	touch $@

CLEANFILES = $(wildcard *.dep)

bootclean:
	rm -f $(BOOTCLEANFILES)
