[
   dot-graph -- V[V is=2[H[_1 KW["graph"] _2 KW["{"]] V[_3]] KW["}"]],
   dot-graph.1:opt -- KW["strict"],
   dot-graph.3:iter-star -- _1,
   dot-digraph -- V[V is=2[H[_1 KW["digraph"] _2 KW["{"]] _3] KW["}"]],
   dot-digraph.1:opt -- KW["strict"],
   dot-digraph.3:iter-star -- _1,
   alias -- _1 KW["="] _2 KW[";"],
   graph-attrs -- H[KW["graph"] KW["["] _1 KW["]"] KW[";"]],
   graph-attrs.1:iter-star-sep -- _1 KW[","],
   node-attrs -- H[ KW["node"] KW["["] _1 KW["]"] KW[";"]],
   node-attrs.1:iter-star-sep -- _1 KW[","],
   edge-attrs -- H[KW["edge"] KW["["] _1 KW["]"] KW[";"]],
   edge-attrs.1:iter-star-sep -- _1 KW[","],
   attr-id -- _1 KW["="] _2,
   attr-num-con -- _1 KW["="] _2,
   node -- H[_1 _2 KW[";"]],
   node.2:opt -- _1,
   Id -- _1,
   QualId -- _1 KW[":"] _2,
   QualId.2:alt -- _1 _2,
   attrs -- KW["["] _1 KW["]"],
   attrs.1:iter-star-sep -- _1 KW[","],
   edge -- H[_1 _2 _3 _4 KW[";"]],
   edge.1:alt -- _1 _2,
   edge.3:iter-sep -- _1 _2,
   edge.3:iter-sep.1:alt -- _1 _2,
   edge.4:opt -- _1,
   sub-graph -- V[H[KW["subgraph"] _1] _2],
   sub-graph.2:opt -- _1,
   sub-graph.2:opt.1:seq -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   sub-graph.2:opt.1:seq.1:iter-star -- _1,
   arrow -- KW["->"],
   line -- KW["--"] 
]
