#!/usr/bin/env bash

SCRIPTDIR=$(cd "$(dirname "$0")" && pwd -P)
STRJAR=$SCRIPTDIR/../share/strategoxt/strategoxt/strategoxt.jar

exec java -Xss8M -cp "$STRJAR" \
  run org.strategoxt.tools.main-gen-renamed-sdf-module "$@"
