#!/usr/bin/env bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
STRJAR=$SCRIPTPATH/../share/strategoxt/strategoxt/strategoxt.jar

exec java -Xss8M -cp "$STRJAR" \
  run org.strategoxt.tools.main-sdf2rtg "$@"
