#!/usr/bin/env bash

set -eu

SCRIPTFILE=${BASH_SOURCE[0]}
SCRIPTDIR=$(dirname "$SCRIPTFILE")
## We consider the case where the script was executed
## - from the source repository, and we use the locally built jar;
## - from the share directory, and we use the jar from there; or
## - from the bin directory, and we use the jar from share
for DISTDIR in "$SCRIPTDIR"/../../buildpoms/build/target/dist "$SCRIPTDIR"/../../.. "$SCRIPTDIR"/..; do
    STRDIR=$DISTDIR/share/strategoxt/strategoxt
    if [ -d "$STRDIR" ]; then
        echo $(cd "$STRDIR" && pwd -P)/strategoxt.jar
        exit 0
    fi
done
echo "Cannot find strategoxt.jar" 1>&2
exit 1
