# Author: Martin Bravenboer <martin@cs.uu.nl>

AC_DEFUN(XT_TERM_DEFINE,
[
  AC_DEFINE(PACKAGE_NAME_TERM(),[ATmakeString("@PACKAGE_NAME@")])
  AC_DEFINE(PACKAGE_TARNAME_TERM(),[ATmakeString("@PACKAGE_TARNAME@")])
  AC_DEFINE(PACKAGE_VERSION_TERM(),[ATmakeString("@PACKAGE_VERSION@")])
  AC_DEFINE(PACKAGE_BUGREPORT_TERM(),[ATmakeString("@PACKAGE_BUGREPORT@")])
  AC_DEFINE(SVN_REVISION_TERM(),[ATmakeString("@SVN_REVISION@")])
])

