#! /bin/sh

./reconf
./configure \
    --prefix=/home/visser/res/XT \
    --with-aterm=/home/xt/ATerm \
    --with-sc-boot=`pwd`/../sc-boot \
    --with-gb-stratego=/home/visser/res/XT/share/gb/stratego.0.7

exit 0

echo "this should'nt be executed"

    --with-gpp=/home/xt/xt \

./configure --prefix=`pwd`/../sc-boot \
	--with-aterm=`pwd`/../aterm \
	--with-cgen=`pwd`/../cgen \
	--with-gpp=`pwd`/../gpp-boot \
	--with-boot=`pwd`/../sc-boot \
	--with-sc-boot=`pwd`/../sc-boot \
	--with-ssl=`pwd`/../ssl \
	--with-srts=`pwd`/../srts 

#	--with-stratego-boot=`pwd` \
#	--with-stratego-boot=/home/xt/xt \
#	--with-stratego-boot=`pwd`/../stratego-boot \

#	--with-cpl=/home/visser/res/sandbox/cpl \
