#! /bin/sh

./reconf
./configure \
    --prefix=/home/xt/xt \
    --with-sc-boot=`pwd`/../sc-boot

exit 0

./configure --prefix=`pwd`/../sc-boot \
	--with-aterm=`pwd`/../aterm \
	--with-cgen=`pwd`/../cgen \
	--with-gpp=`pwd`/../gpp-boot \
	--with-boot=`pwd`/../sc-boot \
	--with-sc-boot=`pwd`/../sc-boot \
	--with-ssl=`pwd`/../ssl \
	--with-srts=`pwd`/../srts 

#	--with-stratego-boot=`pwd` \
#	--with-stratego-boot=/home/xt/xt \
#	--with-stratego-boot=`pwd`/../stratego-boot \

#	--with-cpl=/home/visser/res/sandbox/cpl \
