#! /bin/sh

./reconf
./configure --prefix=/home/xt/xt \
	--with-aterm=/home/xt/xt \
	--with-gpp=/home/xt/xt \
	--with-stratego=/home/xt/xt \
	--with-srts=/home/xt/xt \
	--with-rpmdir=/home/visser/rpm
 
