#! /bin/sh

./reconf
./configure --prefix=`pwd` \
	--with-aterm=`pwd`/../aterm \
	--with-cpl=`pwd`/../cpl \
	--with-gpp=/home/xt/xt \
	--with-stratego=`pwd`/../stratego-spec \
	--with-stratego-rts=`pwd`/../stratego-rts

