#! /bin/sh

./bootstrap
./configure --prefix=`pwd`/.. \
	    --with-sglr=/home/xt/SDF \
	    --with-aterm=/home/xt/ATerm \
	    --with-rpmdir=/home/visser/rpm 

exit 0
	--with-aterm=`pwd`/../aterm \
	--with-cgen=`pwd`/../cgen \
	--with-gpp=`pwd`/../gpp \
	--with-ssl=`pwd`/../ssl \
	--with-srts=`pwd`/../srts 

