#! /bin/sh

./bootstrap
./configure --prefix=/home/xt/XT \
	--with-aterm=/home/xt/XT \
	--with-rpmdir=/home/visser/rpm

#	--with-cpl=/home/xt/CPL \

exit 0

./bootstrap
./configure --prefix=`pwd`/.. \
	--with-aterm=/home/xt/XT \
	--with-cpl=/home/xt/CPL \
	--with-rpmdir=/home/visser/rpm

exit 0

./bootstrap
./configure --prefix=`pwd`/.. \
	--with-aterm=/home/xt/ATerm \
	--with-rpmdir=/home/visser/rpm

#	--with-cpl=/home/xt/CPL

