ATerm SSL_is_int(ATerm t);
ATerm SSL_is_real(ATerm t);
ATerm SSL_int(ATerm t);
ATerm SSL_addi(ATerm x, ATerm y);
ATerm SSL_addr(ATerm x, ATerm y);
ATerm SSL_subti(ATerm x, ATerm y);
ATerm SSL_subtr(ATerm x, ATerm y);
ATerm SSL_muli(ATerm x, ATerm y);
ATerm SSL_mulr(ATerm x, ATerm y);
ATerm SSL_divi(ATerm x, ATerm y);
ATerm SSL_divr(ATerm x, ATerm y);
ATerm SSL_mod(ATerm x, ATerm y);
ATerm SSL_gti(ATerm x, ATerm y);
ATerm SSL_gtr(ATerm x, ATerm y);
ATerm SSL_cos(ATerm x);
ATerm SSL_sin(ATerm x);
ATerm SSL_sqrt(ATerm x);
ATerm SSL_atan2(ATerm x, ATerm y);
ATerm SSL_string_to_int(ATerm x);
ATerm SSL_int_to_string(ATerm x);
ATerm SSL_string_to_real(ATerm x);
ATerm SSL_real_to_string(ATerm x);
ATerm SSL_real(ATerm t);
