[
   Module                    -- KW["module"] _1 _2,
   Module.2:iter-star        -- _1,
   Specification             -- V  [H  [KW["specification"]] _1],
   Specification.1:iter-star -- _1,
   Imports                   -- V  [H  [KW["imports"]] _1],
   Imports.1:iter-star       -- _1,
   Strategies                -- V  [H  [KW["strategies"]] _1],
   Strategies.1:iter-star    -- _1,
   Signature                 -- V  [H  [KW["signature"]] _1],
   Signature.1:iter-star     -- _1,
   Let                       -- KW["let"] _1 KW["in"] _2 KW["end"],
   Let.1:iter-star           -- _1,
   SDefT                     -- _1 KW["("] _2 KW["|"] _3 KW[")"] KW["="] _4,
   SDefT.2:iter-star-sep     -- _1 KW[","],
   SDefT.3:iter-star-sep     -- _1 KW[","],
   Override                  -- KW["override"],
   Extend                    -- KW["extend"],
   Internal                  -- KW["internal"],
   ProceedNoArgs             -- KW["proceed"],
   Proceed                   -- KW["proceed"] KW["("] _1 KW[")"],
   Proceed.1:iter-star-sep   -- _1 KW[","],
   ProceedT                  -- KW["proceed"] KW["("] _1 KW["|"] _2 KW[")"],
   ProceedT.1:iter-star-sep  -- _1 KW[","],
   ProceedT.1:iter-star-sep  -- _1 KW[","],
   AnnoDef                   -- H [ _1 _2 ], 
   VarDec                    -- _1 KW[":"] _2,
   SVar                      -- _1,
   CallT                     -- _1 KW["("] _2 KW["|"] _3 KW[")"],
   CallT.2:iter-star-sep     -- _1 KW[","],
   CallT.3:iter-star-sep     -- _1 KW[","],
   CallDynamic               -- KW["call"] KW["("] _1 KW["|"] _2 KW["|"] _3 KW[")"],
   CallDynamic.2:iter-star-sep -- _1 KW[","],
   CallDynamic.3:iter-star-sep -- _1 KW[","],
   PrimT                     -- KW["prim"] KW["("] _1 KW[","] _2 KW["|"] _3 KW[")"],
   PrimT.2:iter-star-sep     -- _1 KW[","],
   PrimT.3:iter-star-sep     -- _1 KW[","],
   Match                     -- KW["?"] _1,
   Build                     -- KW["!"] _1,
   Scope                     -- KW["{"] _1 KW[":"] _2 KW["}"],
   Scope.1:iter-star-sep     -- _1 KW[","],
   ParenStrat                -- KW["("] _1 KW[")"],
   Fail                      -- KW["fail"],
   Id                        -- KW["id"],
   Seq                       -- _1 KW[";"] _2,
   LChoice                   -- _1 KW["<+"] _2,
   GuardedLChoice            -- _1 KW["<"] _2 KW["+"] _3,
   Rec                       -- KW["rec"] _1 KW["("] _2 KW[")"],
   Not                       -- KW["not"] KW["("] _1 KW[")"],
   LGChoice                  -- _1 KW["<++"] _2,
   Bagof                     -- KW["bagof"] KW["("] _1 KW[")"],
   Some                      -- KW["some"] KW["("] _1 KW[")"],
   One                       -- KW["one"] KW["("] _1 KW[")"],
   All                       -- KW["all"] KW["("] _1 KW[")"],
   Thread                    -- KW["thread"] KW["("] _1 KW[")"],
   IntCong                   -- _1 KW["{"] _2 KW["}"],
   RealCong                  -- _1 KW["{"] _2 KW["}"],
   StrCong                   -- _1 KW["{"] _2 KW["}"],
   OpCong                    -- _1 KW["("] _2 KW[")"] KW["{"] _3 KW["}"],
   OpCong.2:iter-star-sep    -- _1 KW[","],
   Con                       -- _1,
   StrC                      -- _1,
   Expl                      -- _1 KW["#"],
   Int                       -- _1 KW["{"] _2 KW["}"],
   Int.2:iter-star-sep       -- _1 KW[","],
   Real                      -- _1 KW["{"] _2 KW["}"],
   Real.2:iter-star-sep      -- _1 KW[","],
   Str                       -- _1 KW["{"] _2 KW["}"],
   Str.2:iter-star-sep       -- _1 KW[","],
   Op                        -- _1 KW["("] _2 KW[")"] KW["{"] _3 KW["}"],
   Op.2:iter-star-sep        -- _1 KW[","],
   Op.3:iter-star-sep        -- _1 KW[","],
   VarA                      -- _1 _2,
   Var                       -- _1,
   Wld                       -- KW["_"],
   Sorts                     -- V  [H  [KW["sorts"]] _1],
   Sorts.1:iter-star         -- _1,
   Constructors              -- V  [H  [KW["constructors"]] _1],
   Constructors.1:iter-star  -- _1,
   SortVar                   -- _1,
   SortNoArgs                -- _1,
   Sort                      -- _1 KW["("] _2 KW[")"],
   Sort.2:iter-star-sep      -- _1 KW[","],
   OpDecl                    -- _1 KW[":"] _2,
   OpDeclQ                   -- _1 KW[":"] _2,
   OpDeclInj                 -- KW[":"] _1,
   ConstType                 -- _1,
   FunType                   -- _1 KW["->"] _2,
   FunType.1:iter-sep        -- _1 KW["*"]
]
