[
   "dot-0" -- _1,
   dot-graph -- V [ Vis=2 [H[  _1 _2 _3 ]
                KW["{"] _4] KW["}"]],
   dot-graph.1:opt -- KW["strict"],
   dot-graph.2:alt -- KW["graph"] KW["digraph"],
   semicolon -- _1,
   semicolon.1:iter-star -- _1,
   semicolon.1:iter-star.1:seq -- _1 _2,
   semicolon.1:iter-star.1:seq.2:opt -- KW[";"],
   Attr-Stmt -- _1,
   Node-Stmt -- _1,
   Edge-Stmt -- _1,
   SubGraph -- _1,
   alias -- H[_1 KW["="] _2],
   graph -- KW["graph"] KW["["] _1 KW["]"],
   node -- H[KW["node"] KW["["] _1 KW["]"]],
   edge -- H[KW["edge"] KW["["] _1 KW["]"]],
   attr-id -- H[_1 KW["="] _2],
   attr-num-con -- H[_1 KW["="] _2],
   comma -- _1,
   comma.1:iter-star-sep -- _1 KW[","],
   node-stmt -- H[_1 _2],
   node-stmt.2:opt -- _1,
   Id -- _1,
   colon -- _1 KW[":"] _2,
   colon.2:alt -- _1 _2,
   Attr-List -- KW["["] _1 KW["]"],
   edge-stmt -- H[_1 _2 _3 _4],
   edge-stmt.1:alt -- _1 _2,
   edge-stmt.3:iter-sep -- _1 _2,
   edge-stmt.3:iter-sep.1:alt -- _1 _2,
   edge-stmt.4:opt -- _1,
   sub-graph -- KW["subgraph"] _1 _2,
   sub-graph.2:opt -- _1,
   sub-graph.2:opt.1:seq -- KW["{"] _1 KW["}"],
   arrow -- KW["->"],
   line -- KW["--"]
]
