#! /bin/sh

./reconf
./configure --prefix=/home/xt/xt \
	--with-aterm=/home/xt/ATerm \
	--with-gpp=/home/xt/xt \
	--with-stratego=/home/xt/xt \
	--with-stratego-rts=/home/xt/xt \
	--with-ssl=/home/xt/xt

