#!/bin/sh

for option in $*; do
  case $option in
  -help | --help | -h)
    echo "Usage: strcflags [PACKAGE]..." >&2
    echo "Lists strc command-line options for using PACKAGEs." >&2
    echo "Example:" >&2
    echo "  \$ strc -i foo.str \$(strcflags stratego-lib java-front)" >&2
    exit 1
    ;;
  esac
done

pkg-config --print-errors --variable=strcflags $*
