#! /bin/sh
#
# Copyright (C) 2000 Eelco Visser <visser@acm.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.
#
# $Id: visamb-check,v 1.1.1.1 2001/05/30 15:19:02 mdejonge Exp $
#

# Exit immediately if a command exits with a non-zero status.
set -e

sdf2table -i test.sdf -o test.tbl
sglr -t -p test.tbl -i input.test -o input.tree
./visamb -i input.tree -o test.ambs

sdf2table -i Exp.sdf -o Exp.tbl
sglr -t -p Exp.tbl -i input.exp -o input.tree
./visamb -i input.tree -o exp.ambs

rm -f test.tbl input.tree test.ambs Exp.tbl exp.ambs
