[
   DotGraph -- V[ V is=2 [ H[ KW["graph"] _1 KW["{"]] _2] KW["}"]],
   DotGraph.2:iter-star -- _1,
   StrictDotGraph -- V[ V is=2[ H[ KW["strict"] KW["graph"]  _1 KW["{"] ] _2 ] KW["}"]],
   StrictDotGraph.2:iter-star -- _1,
   DotDigraph -- V[ V is=2[ H[ KW["digraph"] _1 KW["{"] ] _2 ] KW["}"] ],
   DotDigraph.2:iter-star -- _1,
   StrictDotDigraph -- V[ V is=2[ H[ KW["strict"] KW["digraph"] _1 KW["{"] ] _2 ] KW["}"] ],
   StrictDotDigraph.2:iter-star -- _1,
   Alias -- H[ _1 KW["="] _2 KW[";"] ],
   GraphAttrs -- H[ KW["graph"] KW["["] _1 KW["]"] KW[";"] ],
   GraphAttrs.1:iter-star-sep -- _1 KW[","],
   NodeAttrs -- H[ KW["node"] KW["["] _1 KW["]"] KW[";"] ],
   NodeAttrs.1:iter-star-sep -- _1 KW[","],
   EdgeAttrs -- H[ KW["edge"] KW["["] _1 KW["]"] KW[";"] ],
   EdgeAttrs.1:iter-star-sep -- _1 KW[","],
   AttrId -- _1 KW["="] _2,
   AttrNumCon -- _1 KW["="] _2,
   Node -- H[_1 _2 KW[";"]],
   Node.2:opt -- _1,
   Id -- _1,
   QualId -- _1 KW[":"] _2,
   QualId -- _1 KW[":"] _2,
   Attrs -- KW["["] _1 KW["]"],
   Attrs.1:iter-star-sep -- _1 KW[","],
   EdgeNoAttrs -- H[ _1 _2 KW[";"] ],
   EdgeNoAttrs.2:iter -- _1,
   Edge -- H[ _1 _2 _3 KW[";"] ],
   Edge.2:iter -- _1,
   SubGraph -- V[ V is =2 [ H[ KW["subgraph"] _1 KW["{"] ] _2] KW["}"] ],
   SubGraph.2:iter-star -- _1,
   SubGraphNoArgs -- KW["subgraph"] _1,
   Arrow -- H[ KW["->"] _1 ],
   Line -- H[ KW["--"] _1 ]
]
