[
   DotGraph                     -- KW["graph"] _1 KW["{"] _2 KW["}"],                
   DotGraph.2:iter-star         -- _1,                                               
   StrictDotGraph               -- KW["strict"] KW["graph"] _1 KW["{"] _2 KW["}"],   
   StrictDotGraph.2:iter-star   -- _1,                                               
   DotDigraph                   -- KW["digraph"] _1 KW["{"] _2 KW["}"],              
   DotDigraph.2:iter-star       -- _1,                                               
   StrictDotDigraph             -- KW["strict"] KW["digraph"] _1 KW["{"] _2 KW["}"], 
   StrictDotDigraph.2:iter-star -- _1,                                               
   Alias                        -- _1 KW["="] _2 KW[";"],                            
   GraphAttrs                   -- KW["graph"] KW["["] _1 KW["]"] KW[";"],           
   GraphAttrs.1:iter-star-sep   -- _1 KW[","],                                       
   NodeAttrs                    -- KW["node"] KW["["] _1 KW["]"] KW[";"],            
   NodeAttrs.1:iter-star-sep    -- _1 KW[","],                                       
   EdgeAttrs                    -- KW["edge"] KW["["] _1 KW["]"] KW[";"],            
   EdgeAttrs.1:iter-star-sep    -- _1 KW[","],                                       
   AttrId                       -- _1 KW["="] _2,                                    
   AttrNumCon                   -- _1 KW["="] _2,                                    
   Node                         -- _1 _2 KW[";"],                                    
   Node.2:opt                   -- _1,                                               
   Id                           -- _1,                                               
   QualId                       -- _1 KW[":"] _2,                                    
   QualId                       -- _1 KW[":"] _2,                                    
   Attrs                        -- KW["["] _1 KW["]"],                               
   Attrs.1:iter-star-sep        -- _1 KW[","],                                       
   EdgeNoAttrs                  -- _1 _2 KW[";"],                                    
   EdgeNoAttrs.2:iter           -- _1,                                               
   Edge                         -- _1 _2 _3 KW[";"],                                 
   Edge.2:iter                  -- _1,                                               
   SubGraph                     -- KW["subgraph"] _1 KW["{"] _2 KW["}"],             
   SubGraph.2:iter-star         -- _1,                                               
   SubGraphNoArgs               -- KW["subgraph"] _1,                                
   Arrow                        -- KW["->"] _1,                                      
   Line                         -- KW["--"] _1                                       
]
