#!/bin/sh

rm -f config.cache config.log config.status acconfig.h aclocal.m4

touch README
touch NEWS

autoxt
aclocal -I .
autoconf -f 
#--warnings=all
automake -a 
#--warnings=all  --warnings=no-portability
