#!/bin/sh

rm -f config.cache config.log acconfig.h aclocal.m4

autoxt || exit 1
aclocal -I . || exit 1
libtoolize --force || glibtoolize --force || exit 1
autoconf -f || exit 1
automake -a || exit 1
