#!/bin/sh

./bootstrap
./configure --prefix=/home/xt/XT \
	--with-sglr=/home/xt/XT \
	--with-pgen=/home/xt/XT \
	--with-rpmdir=/home/visser/rpm

exit 0

./bootstrap
./configure --prefix=`pwd`/.. \
	--with-sglr=/home/xt/SDF \
	--with-pgen=/home/xt/SDF \
	--with-rpmdir=/home/visser/rpm

exit 0

./reconf
./configure --prefix=/home/xt/xt \
	--with-sglr=/home/xt/SDF \
	--with-pgen=/home/xt/SDF \
	--with-sc=/home/xt/xt \
	--with-gpp=/home/xt/xt \
	--with-sdf-tools=/home/xt/xt \
	--with-stratego-tools=/home/xt/xt  \
	--with-asfix-tools=/home/xt/xt \
	--with-rpmdir=/home/visser/rpm

# --prefix=`pwd`/.. \
#	--with-stratego=/home/visser/res/Stratego
