SUFFIXES += .strxml .strxml2

.strxml.rtree :
	$(XML_TOOLS)/libexec/parse-stratego-xml-info -i $< | \
	$(XML_TOOLS)/libexec/process-stratego-xml-doc | \
	$(XML_TOOLS)/libexec/process-stratego-xml-info | \
	$(STRATEGO_FRONT)/bin/meta-explode | \
	$(STRATEGO_FRONT)/bin/stratego-desugar -o $@

.strxml2.rtree :
	$(XML_TOOLS)/libexec/parse-stratego-xml-info -i $< | \
	$(XML_TOOLS)/libexec/process-stratego-xml-doc | \
	$(XML_TOOLS)/libexec/process-stratego-xml-info | \
	$(XML_TOOLS)/libexec/process-stratego-xml-interpret --rhg-nf $(RHGNF) | \
	$(STRATEGO_FRONT)/bin/meta-explode | \
	$(STRATEGO_FRONT)/bin/stratego-desugar -o $@