[
   URI                        -- _1 KW["://"] _2,
   URI.2:iter-star-sep        -- _1 KW["/"],
   Language                   -- _1,
   ID                         -- _1 KW["."] _2 KW["."] _3,
   Subsequent                 -- KW["subsequent"] KW["("] _1 KW[")"],
   Anonymous                  -- KW["anonymous"] KW["("] _1 KW[")"],
   ExternalDef                -- KW["context"] KW["("] _1 KW[")"],
   Unique                     -- KW["u"] KW["("] _1 KW[")"],
   Unique                     -- KW["u"] KW["("] KW["*"] KW[")"],
   NonUnique                  -- KW["*"],
   COMPLETION-URI             -- _1,
   COMPLETION-Language        -- _1,
   COMPLETION-Segment         -- _1,
   COMPLETION-Qualifier       -- _1,
   Index                      -- _1,
   Index.1:iter-star          -- _1,
   Partition                  -- KW["partition"] _1 _2,
   Partition.2:iter-star      -- _1,
   Global                     -- KW["global"] _1,
   Global                     -- KW["global"] _1 KW["{"] _2 KW["}"],
   Global.2:iter-star         -- _1,
   Def                        -- KW["binding"] KW["instance"] _1,
   Alias                      -- KW["alias"] _1 KW["->"] _2,
   Use                        -- KW["binding"] KW["prospect"] _1,
   Prop                       -- KW["property"] _1 KW["."] _2 KW["="] _3,
   DoneTask                   -- KW["result"] _1 KW["="] _2,
   FailTask                   -- KW["error"] _1 KW["="] _2,
   StoreTask                  -- KW["task"] _1 _2,
   StoreTaskDep               -- KW["dependency"] _1 KW["->"] _2,
   COMPLETION-Index           -- _1,
   COMPLETION-Partition       -- _1,
   COMPLETION-Entry           -- _1,
   Task                       -- KW["task"] _1 KW["depends"] KW["on"] _2 _3,
   Task.2:iter-star-sep       -- _1 KW[","],
   Resolve                    -- KW["resolve"] _1 KW["/"] _2 KW["."] _3 _4 _5,
   Choice                     -- V  [H  [KW["choose"]] _1],
   Choice.1:iter-sep          -- _1 KW["||"],
   PropCalc                   -- KW["calculate"] _1 KW["of"] _2,
   Match                      -- KW["match"] _1 KW["("] _2 KW[")"] KW["with"] _3,
   Match.2:iter-star-sep      -- _1 KW[","],
   COMPLETION-Task            -- _1,
   COMPLETION-Instruction     -- _1,
   Done                       -- KW["done"] _1,
   Fail                       -- KW["failed"] _1,
   Dependency                 -- V  [H  [KW["depends"] KW["on"]] _1],
   Dependency.1:iter-star-sep -- _1 KW[","],
   Result                     -- KW["result"] _1,
   COMPLETION-Result          -- _1,
   COMPLETION-Term            -- _1
]