#define get_conf_version() 	ATmakeString("0.9beta2")
#define get_conf_package() 	ATmakeString("sc-boot")
#define get_conf_prefix() 	ATmakeString("/home/xt/XT")
#define get_conf_datadir() 	ATmakeString("/home/xt/XT/share")
#define get_conf_pkgdatadir() 	ATmakeString("/home/xt/XT/share/sc")
