/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/svn/convert/StrategoXT/obsolete/sc-boot/src/stratego.yy.c,v 1.25 2002/09/20 06:04:47 stratego Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 95
#define YY_END_OF_BUFFER 96
static yyconst short int yy_acclist[377] =
    {   0,
        8,    8,   96,   94,   95,    8,   94,   95,   10,   95,
       43,   94,   95,   91,   94,   95,   85,   94,   95,   94,
       95,   70,   94,   95,   71,   94,   95,   14,   64,   94,
       95,   56,   94,   95,   66,   94,   95,   94,   95,   53,
       94,   95,   94,   95,   92,   94,   95,   68,   94,   95,
       67,   94,   95,   78,   94,   95,   15,   65,   94,   95,
       79,   94,   95,   42,   94,   95,   44,   94,   95,   89,
       90,   94,   95,   76,   94,   95,   52,   94,   95,   77,
       94,   95,   86,   94,   95,   62,   89,   90,   94,   95,
       88,   94,   95,   88,   94,   95,   88,   94,   95,   88,

       94,   95,   88,   94,   95,   88,   94,   95,   88,   94,
       95,   88,   94,   95,   88,   94,   95,   88,   94,   95,
       88,   94,   95,   88,   94,   95,   88,   94,   95,   88,
       94,   95,   88,   94,   95,   73,   94,   95,   84,   94,
       95,   75,   94,   95,   95,   29,   95,   95,   53,   95,
       95,   95,   21,   95,   28,   95,   95,   27,   95,   27,
       95,   27,   95,   27,   95,   27,   95,    7,   95,    6,
       95,    7,   95,    8,   90,   11,   63,   57,   59,   92,
       81,   12,   54,   69,   55,   58,   83,   82,   89,   90,
       87,   88,   88,   88,   88,   88,   33,   88,   88,   40,

       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   72,   74,   24,   25,
       28,   27,   27,   27,   27,   27,   27,   90,   80,    9,
       93,   60,   61,   37,   88,   88,   88,   88,   88,   39,
       88,   88,   38,   88,   35,   88,   88,   88,   31,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   27,
       27,   27,   27,   27,   88,   88,   32,   88,   88,   88,
       88,   49,   88,   88,   88,   88,   34,   88,   88,   88,
       46,   88,   88,   88,   27,   27,   27,   27,   27,   22,
       23,   41,   88,   88,   88,   88,   88,   88,   18,   88,

       88,   88,   47,   88,   88,   88,   45,   88,   27,   27,
       18,   27,   27,   27,   88,   88,   13,   88,   88,   88,
       51,   88,   88,   88,   36,   88,   27,   27,   27,   27,
       88,   16,   88,   88,   88,   88,   88,   16,   27,   27,
       27,   27,   88,   20,   88,   30,   88,   88,   88,   50,
       88,   20,   27,   27,   27,    1,   88,   19,   88,   88,
       19,   27,   27,    2,   88,   17,   88,   26,   17,   27,
       88,    3,   48,   88,    4,    5
    } ;

static yyconst short int yy_accept[314] =
    {   0,
        1,    2,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    4,    6,    9,   11,   14,   17,   20,
       22,   25,   28,   32,   35,   38,   40,   43,   45,   48,
       51,   54,   57,   61,   64,   67,   70,   74,   77,   80,
       83,   86,   91,   94,   97,  100,  103,  106,  109,  112,
      115,  118,  121,  124,  127,  130,  133,  136,  139,  142,
      145,  146,  148,  149,  151,  152,  153,  155,  157,  158,
      160,  162,  164,  166,  168,  170,  172,  174,  175,  176,
      177,  178,  179,  180,  180,  181,  182,  183,  183,  183,
      184,  185,  186,  186,  186,  187,  188,  189,  191,  192,

      192,  192,  192,  193,  194,  195,  196,  197,  199,  200,
      202,  203,  204,  205,  206,  207,  208,  209,  210,  211,
      212,  213,  214,  215,  216,  217,  218,  219,  220,  221,
      222,  222,  223,  224,  225,  226,  227,  228,  228,  228,
      229,  230,  230,  231,  232,  232,  232,  234,  234,  234,
      234,  236,  237,  238,  239,  240,  242,  243,  245,  247,
      248,  249,  251,  252,  253,  254,  255,  256,  257,  258,
      259,  260,  260,  261,  262,  263,  264,  265,  265,  265,
      265,  265,  265,  265,  265,  266,  267,  269,  270,  271,
      272,  274,  275,  276,  277,  279,  280,  281,  283,  284,

      285,  285,  286,  287,  288,  289,  290,  290,  290,  291,
      292,  292,  292,  292,  294,  295,  296,  297,  298,  299,
      301,  302,  303,  305,  306,  307,  309,  309,  310,  311,
      313,  314,  315,  315,  315,  315,  315,  315,  316,  317,
      319,  320,  321,  323,  324,  325,  327,  327,  328,  329,
      330,  331,  331,  331,  331,  331,  331,  332,  334,  335,
      336,  337,  338,  338,  340,  341,  342,  343,  343,  343,
      343,  343,  343,  344,  346,  348,  349,  350,  352,  352,
      354,  355,  356,  356,  356,  356,  356,  357,  358,  360,
      361,  361,  363,  364,  364,  364,  364,  365,  366,  368,

      369,  371,  371,  371,  371,  372,  372,  372,  373,  375,
      376,  377,  377
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   30,   30,   40,   41,   42,
       43,   44,   30,   45,   46,   47,   48,   49,   50,   30,
       51,   30,   52,   53,   54,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[55] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    3,
        1,    1,    2,    2,    1,    2,    1,    1,    1,    1,
        1,    1,    1,    2,    1,    1,    1,    1,    2,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    1,    1,    1
    } ;

static yyconst short int yy_base[322] =
    {   0,
        0,    0,    0,    0,   54,    0,    0,    0,  106,  107,
        0,    0,  491,  492,  488,  492,  492,  492,  492,    0,
      479,  492,  478,  100,  492,   99,  492,  103,  100,  106,
      492,  111,  466,  492,  492,  492,  476,  492,   95,  492,
      492,  475,  474,  107,  114,  115,  118,  119,  124,  126,
      127,  129,  128,  131,  141,  147,  134,  430,  428,  492,
      492,  492,  471,  492,  470,  108,  492,    0,  444,    0,
      437,  428,  428,  115,  492,  492,  120,  473,    0,  492,
      492,  492,  492,  453,  149,  492,  492,  470,  456,  492,
      492,  492,  423,  427,  458,  492,  492,  458,  492,  432,

      424,  426,  454,  146,  140,  133,  154,  453,  157,  452,
      158,  166,  171,  173,  177,  180,  181,  182,  179,  184,
      185,  186,  187,  189,  188,  492,  492,  492,  492,    0,
      419,    0,  416,  424,  418,  420,  411,  420,  412,    0,
      492,  450,  492,  436,  410,  419,  492,  412,  414,  400,
      436,  192,  193,  196,  194,  435,  197,  434,  433,  199,
      200,  432,  203,  201,  205,  207,  206,  215,  210,  217,
      218,  407,  397,  394,  403,  395,  405,  398,  400,  389,
      398,  392,  378,  394,  219,  222,  418,  233,  239,  240,
      417,  238,  244,  241,  416,  246,  248,  415,  250,  251,

      372,  378,  382,  375,  389,  372,  379,  377,  492,  492,
      374,  382,  369,  403,  249,  252,  254,  256,  257,  402,
      255,  258,  401,  263,  266,  400,  376,  361,  376,    0,
      359,  370,  362,  364,  350,  358,  369,  260,  261,  389,
      264,  267,  388,  265,  272,  387,  353,  349,  343,  345,
      355,  339,  343,  356,  354,  340,  273,  376,  280,  281,
      283,  293,  351,    0,  338,  338,  343,  348,  340,  329,
      334,  317,  287,  341,  340,  294,  300,  337,  311,    0,
      310,  308,  299,  296,  306,  285,  492,  301,  328,  302,
      283,    0,  287,  297,  299,  292,  492,  304,  315,  492,

        0,  289,  276,  268,  307,  267,  285,  492,  309,  492,
      492,  492,  353,  357,  314,  360,  363,  366,  369,  372,
      376
    } ;

static yyconst short int yy_def[322] =
    {   0,
      312,    1,  313,  313,  312,    5,  313,  313,  314,  314,
      313,  313,  312,  312,  312,  312,  312,  312,  312,  315,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  316,  312,  312,  312,
      312,  316,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  318,  312,  319,
      319,  319,  319,  319,  312,  312,  312,  312,  320,  312,
      312,  312,  312,  312,  312,  312,  312,  321,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  316,  312,  312,

      312,  312,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  312,  312,  312,  312,  318,
      312,  319,  319,  319,  319,  319,  319,  312,  312,  320,
      312,  321,  312,  312,  312,  312,  312,  312,  312,  312,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  312,  319,  319,  319,  319,  319,  312,  312,  312,
      312,  312,  312,  312,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,

      312,  319,  319,  319,  319,  319,  312,  312,  312,  312,
      312,  312,  312,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  312,  319,  319,  319,
      319,  319,  312,  312,  312,  312,  312,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  312,  319,  319,  319,
      319,  312,  312,  312,  312,  312,  317,  317,  317,  317,
      317,  317,  312,  319,  319,  319,  319,  312,  312,  312,
      312,  312,  317,  317,  317,  317,  317,  317,  312,  319,
      319,  319,  312,  312,  312,  312,  312,  317,  317,  317,
      312,  319,  319,  312,  312,  312,  312,  317,  317,  312,

      319,  312,  312,  312,  317,  312,  312,  312,  317,  312,
      312,    0,  312,  312,  312,  312,  312,  312,  312,  312,
      312
    } ;

static yyconst short int yy_nxt[547] =
    {   0,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   46,   43,   43,   47,   43,   43,   48,   49,
       50,   51,   52,   53,   54,   55,   56,   43,   43,   57,
       43,   58,   59,   60,   61,   62,   62,   61,   61,   61,
       61,   63,   61,   61,   61,   61,   61,   64,   65,   61,
       66,   61,   61,   61,   67,   61,   61,   68,   61,   69,
       61,   61,   68,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   71,   70,   70,   70,   72,   70,   73,   74,

       70,   70,   70,   70,   70,   61,   61,   61,   76,   76,
       82,   84,   87,   89,   85,   85,   99,   88,   90,   86,
       83,   95,   91,   99,   99,   92,  100,   99,   99,  101,
       96,   77,   77,   99,  102,   99,   99,   99,   99,   93,
       99,   93,   99,   99,  105,   94,  104,   94,  107,   99,
       99,  138,  108,  136,  139,   99,   99,  106,  111,  109,
      110,  137,   89,   99,   85,  117,   99,   99,  112,  113,
      114,  125,  116,  119,  153,   99,  152,  115,  118,  120,
       99,  123,   99,  121,  124,  151,   99,  122,   99,   99,
       99,   99,  154,   99,   99,   99,   99,   99,   99,  157,

      155,   99,   99,   99,  156,   99,   99,  159,   99,   99,
       99,  160,   99,  162,   99,   99,   99,  158,  161,   99,
      165,  163,  171,  164,   99,  166,   99,   99,   99,  167,
      168,   99,  169,  170,  185,  187,  188,  192,  186,  193,
      191,  195,   99,  190,  189,  197,  194,   99,   99,   99,
       99,  199,  196,   99,  214,   99,  198,   99,   99,   99,
       99,   99,  200,   99,   99,   99,   99,   99,  215,   99,
       99,  222,   99,   99,   99,   99,   99,  216,  217,  218,
      225,   99,   99,  220,  219,  226,  241,  221,  240,   99,
       99,  223,   99,  238,  224,  242,   99,  245,  239,  246,

      260,  243,   99,   99,  244,  273,  258,  257,  262,   99,
       99,   99,  261,   99,  259,  275,   99,   79,   99,  311,
      310,  308,  307,  306,   99,  274,  304,  276,  289,  303,
      302,  277,  301,  288,  290,  278,  300,   99,  297,  296,
      295,  294,  293,  298,  292,  291,   99,  299,  305,   99,
       99,  287,  309,   61,   61,   61,   61,   75,   75,   75,
       75,   98,   98,   98,  103,  103,  103,  130,  286,  130,
      132,  285,  132,  140,  284,  140,  142,  142,  142,  142,
      283,  282,  281,  280,  279,   99,  272,  271,  270,  269,
      268,  267,  266,  265,  264,  263,   99,   99,   99,  256,

      255,  254,  253,  252,  251,  250,  249,  248,  247,   99,
       99,   99,   99,  237,  236,  235,  234,  233,  232,  231,
      230,  229,  228,  227,   99,   99,   99,   99,  213,  212,
      211,  210,  209,  208,  207,  206,  205,  204,  203,  202,
      201,   99,   99,   99,   99,   99,  184,  183,  182,  181,
      180,  144,  143,  179,  178,  177,  176,  175,  174,  173,
      172,   99,   99,   99,  150,  149,  148,   99,  147,  146,
      145,  144,  143,  141,   78,  135,  134,  133,  131,  129,
      128,  127,  126,   99,   99,   99,   97,   81,   80,   78,
      312,   13,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312
    } ;

static yyconst short int yy_chk[547] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    9,   10,
       24,   26,   28,   29,   26,   29,   44,   28,   30,   26,
       24,   32,   30,   45,   46,   30,   39,   47,   48,   39,
       32,    9,   10,   49,   39,   50,   51,   53,   52,   30,
       54,   66,  106,   57,   45,   30,   44,   66,   47,  105,
       55,   77,   48,   74,   77,  104,   56,   46,   49,   48,
       48,   74,   85,  107,   85,   54,  109,  111,   50,   51,
       52,   57,   53,   55,  106,  112,  105,   52,   54,   55,
      113,   56,  114,   55,   56,  104,  115,   55,  119,  116,
      117,  118,  107,  120,  121,  122,  123,  125,  124,  112,

      109,  152,  153,  155,  111,  154,  157,  114,  160,  161,
      164,  115,  163,  117,  165,  167,  166,  113,  116,  169,
      120,  118,  125,  119,  168,  121,  170,  171,  185,  121,
      122,  186,  123,  124,  152,  154,  155,  163,  153,  164,
      161,  166,  188,  160,  157,  168,  165,  192,  189,  190,
      194,  170,  167,  193,  185,  196,  169,  197,  215,  199,
      200,  216,  171,  217,  221,  218,  219,  222,  186,  238,
      239,  194,  224,  241,  244,  225,  242,  188,  189,  190,
      199,  245,  257,  192,  190,  200,  218,  193,  217,  259,
      260,  196,  261,  215,  197,  219,  273,  224,  216,  225,

      242,  221,  262,  276,  222,  257,  239,  238,  245,  277,
      288,  290,  244,  298,  241,  260,  305,  315,  309,  307,
      306,  304,  303,  302,  299,  259,  296,  261,  276,  295,
      294,  262,  293,  273,  277,  262,  291,  289,  286,  285,
      284,  283,  282,  288,  281,  279,  278,  290,  298,  275,
      274,  272,  305,  313,  313,  313,  313,  314,  314,  314,
      314,  316,  316,  316,  317,  317,  317,  318,  271,  318,
      319,  270,  319,  320,  269,  320,  321,  321,  321,  321,
      268,  267,  266,  265,  263,  258,  256,  255,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  243,  240,  237,

      236,  235,  234,  233,  232,  231,  229,  228,  227,  226,
      223,  220,  214,  213,  212,  211,  208,  207,  206,  205,
      204,  203,  202,  201,  198,  195,  191,  187,  184,  183,
      182,  181,  180,  179,  178,  177,  176,  175,  174,  173,
      172,  162,  159,  158,  156,  151,  150,  149,  148,  146,
      145,  144,  142,  139,  138,  137,  136,  135,  134,  133,
      131,  110,  108,  103,  102,  101,  100,   98,   95,   94,
       93,   89,   88,   84,   78,   73,   72,   71,   69,   65,
       63,   59,   58,   43,   42,   37,   33,   23,   21,   15,
       13,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "stratego.lx"
#define INITIAL 0
#line 2 "stratego.lx"

#include <aterm2.h>
#include <srts/stratego.h>
#include "stratego.grm.tab.h"
#include "options.h"

static void eat_comment();
static void eat_c_comment();
static ATerm mkstring();
void yyerror(char *msg);

FILE *outfile;

#define lexerror(x, y) fprintf(stderr, "%s %s\n", x, y)

#define YY_DECL  int yylex(YYSTYPE *lvalp)

extern char file_name[256];

int line = 0;

/*
lcid		{lcstart}{idchars}*
ucid		{ucstart}{idchars}*
lcid		{idchars}+
ucid		{idchars}+
*/

#define COMM 1
#define MODNAME 2
#define IMP 3
#define LIT 4
#define STARTLIT 5

#line 680 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 55 "stratego.lx"


		/* Literate programs */ 

#line 836 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 313 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 492 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 59 "stratego.lx"
BEGIN LIT;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 60 "stratego.lx"
BEGIN LIT;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 61 "stratego.lx"
BEGIN INITIAL;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 62 "stratego.lx"
BEGIN INITIAL;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 63 "stratego.lx"
BEGIN INITIAL;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 64 "stratego.lx"
; /* ignore newlines */
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 65 "stratego.lx"
; /* ignore text */
	YY_BREAK
/* Layout */
case 8:
YY_RULE_SETUP
#line 69 "stratego.lx"
; /* ignore whitespace */
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 70 "stratego.lx"
; /* ignore comments */
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 71 "stratego.lx"
line++; /* ignore newlines */
	YY_BREAK
/* Comments (SML style) */
case 11:
YY_RULE_SETUP
#line 75 "stratego.lx"
eat_comment();
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 76 "stratego.lx"
eat_c_comment();
	YY_BREAK
/* Module header */
case 13:
YY_RULE_SETUP
#line 80 "stratego.lx"
BEGIN MODNAME; return MODULE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 81 "stratego.lx"
return ASTERISK;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 82 "stratego.lx"
return EQ;
	YY_BREAK
/* Imports */
case 16:
YY_RULE_SETUP
#line 86 "stratego.lx"
BEGIN MODNAME; return IMPORTS;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 88 "stratego.lx"
BEGIN INITIAL; return STRATEGIES;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 89 "stratego.lx"
BEGIN INITIAL; return RULES;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 90 "stratego.lx"
BEGIN INITIAL; return SIGNATURE;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 91 "stratego.lx"
BEGIN INITIAL; return OVERLAYS;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 93 "stratego.lx"
BEGIN INITIAL; return GT;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 95 "stratego.lx"
BEGIN INITIAL; return DUMP;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 96 "stratego.lx"
BEGIN INITIAL; return LOAD;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 98 "stratego.lx"
eat_comment();
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 99 "stratego.lx"
eat_c_comment();
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 101 "stratego.lx"
BEGIN LIT;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 103 "stratego.lx"
(*lvalp).term = ATmakeString(yytext); return LCID;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 104 "stratego.lx"
(*lvalp).term = ATmakeString(yytext); return UCID;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 106 "stratego.lx"
line++; /* ignore whitespace */
	YY_BREAK
/* keywords */
case 30:
YY_RULE_SETUP
#line 111 "stratego.lx"
return OVERRIDE;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 112 "stratego.lx"
return MU;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 113 "stratego.lx"
return FAIL;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 114 "stratego.lx"
return SUCC;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 116 "stratego.lx"
return SOMETOK;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 117 "stratego.lx"
return ONE;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 118 "stratego.lx"
return THREAD;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 119 "stratego.lx"
return ALL;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 120 "stratego.lx"
return NOT;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 121 "stratego.lx"
return LET;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 122 "stratego.lx"
return IN;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 124 "stratego.lx"
return BAGOF;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 126 "stratego.lx"
return MATCHe;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 127 "stratego.lx"
return BUILDe;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 129 "stratego.lx"
return AS;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 131 "stratego.lx"
return WHERE;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 132 "stratego.lx"
return TEST;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 133 "stratego.lx"
return SORTS;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 135 "stratego.lx"
return CONSTRUCTORS;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 136 "stratego.lx"
return PRIM;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 138 "stratego.lx"
return STRATEGO;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 139 "stratego.lx"
return SCRIPT;
	YY_BREAK
/* Operators */
case 52:
YY_RULE_SETUP
#line 143 "stratego.lx"
return BACKSLASH;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 144 "stratego.lx"
return DOT;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 145 "stratego.lx"
return BACKARROW;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 146 "stratego.lx"
return ASSIGN;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 147 "stratego.lx"
return PLUS;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 148 "stratego.lx"
return PLUSPLUS;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 149 "stratego.lx"
return LTPLUS;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 150 "stratego.lx"
return PLUSGT;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 151 "stratego.lx"
return LTPLUSPLUS;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 152 "stratego.lx"
return PLUSGT;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 153 "stratego.lx"
return UNDERSCORE;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 154 "stratego.lx"
return STARSTAR;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 155 "stratego.lx"
return ASTERISK;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 156 "stratego.lx"
return EQ;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 157 "stratego.lx"
return COMMA;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 158 "stratego.lx"
return SEMICOLON;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 159 "stratego.lx"
return COLON;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 160 "stratego.lx"
return DOUBLECOLON;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 161 "stratego.lx"
return LPAREN;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 162 "stratego.lx"
return RPAREN;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 163 "stratego.lx"
return LCURLYBAR;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 164 "stratego.lx"
return LCURLY;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 165 "stratego.lx"
return BARRCURLY;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 166 "stratego.lx"
return RCURLY;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 167 "stratego.lx"
return LBRACK;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 168 "stratego.lx"
return RBRACK;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 169 "stratego.lx"
return LT;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 170 "stratego.lx"
return GT;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 171 "stratego.lx"
return LONGARROW;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 172 "stratego.lx"
return ARROW;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 173 "stratego.lx"
return DOUBLEARROW;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 174 "stratego.lx"
return LEFTDOUBLEARROW;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 175 "stratego.lx"
return BAR;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 176 "stratego.lx"
return EXPLODE;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 177 "stratego.lx"
return MODIFIER;
	YY_BREAK
/* Identifiers, strings and numbers */
case 87:
YY_RULE_SETUP
#line 181 "stratego.lx"
(*lvalp).term = ATmakeString(yytext); return LID;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 182 "stratego.lx"
(*lvalp).term = ATmakeString(yytext); return LCID;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 183 "stratego.lx"
(*lvalp).term = ATmakeString(yytext); return UCID;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 184 "stratego.lx"
(*lvalp).term = ATmakeString(yytext+1); return UCID;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 185 "stratego.lx"
(*lvalp).term = mkstring(); return STRINGTOK;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 186 "stratego.lx"
(*lvalp).num  = atoi(yytext); return INT;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 187 "stratego.lx"
(*lvalp).real = atof(yytext); return REAL;
	YY_BREAK
/* All other characters are wrong */
case 94:
YY_RULE_SETUP
#line 191 "stratego.lx"
lexerror ("ignoring illegal character", yytext);
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMM):
case YY_STATE_EOF(MODNAME):
case YY_STATE_EOF(IMP):
case YY_STATE_EOF(LIT):
case YY_STATE_EOF(STARTLIT):
#line 193 "stratego.lx"
{BEGIN(INITIAL); 
		 // ATfprintf(stderr, "%s: %d lines\n", file_name, line); 
		 yyterminate();}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 197 "stratego.lx"
ECHO;
	YY_BREAK
#line 1421 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 313 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 313 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 312);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 197 "stratego.lx"


/*
 * Function which skips comment chars. The function allows '*' to
 * occure within comments.
 */

static void eat_comment()
{
   char c;
   
   while( 1 )
   {
      /* get a character */
      c = input();

      if(c == EOF)
        yyerror("unclosed comment at end of file");
		
      /* if it equals '*" and the next character equals ')' then
       * the end of the comment is reached.
       */
      while( c == '*' )
      {
         c = input();
         if( c == ')' )
            return;
      }
   }
}


static void eat_c_comment()
{
   char c;
   
   while( 1 )
   {
      /* get a character */
      c = input();
      
      if(c == EOF)
        yyerror("unclosed comment at end of file");

      /* if it equals '*" and the next character equals '/' then
       * the end of the comment is reached.
       */
      while( c == '*' )
      {
         c = input();
         if( c == '/' )
            return;
      }
   }
}

static char* resize_buf( char* buf, int size)
{
   buf = (char*)realloc( buf, size );
   assert( buf != NULL );
   return buf;
}

#define CHECK(buf, size, ind ) \
	if( ind == size ){ size *= 2; buf = resize_buf( buf, size );}

/*
 * This functions parses a quoted string and accepts
 * escaped quotes (e.g., "hello \"world\"") within strings.
 */
static ATerm mkstring()
{
   ATerm theString;
   char* buf = NULL;
   int c;
   int size = 512;
   int ind  = 0;
   
   /* use dynamically resizable buffer to store string */
   buf = resize_buf( buf, size );

   /* add opening quote */
   CHECK( buf, size, ind );
   buf[ind++] = '"';

   while( 1 )
   {
      c = input();

      if( c == '\"' )
         break;

      if( c <= 0 )
      {
         yyerror( "String not terminated at eof" );
         return NULL;
      }
      
      /* Handle escaped character */
      if( c == '\\' )
      {
         CHECK( buf, size, ind );
         buf[ind++] = c;
         c = input();
      }

      CHECK( buf, size, ind );
      buf[ind++] = c;
   }
   /* Add closing quote */
   CHECK( buf, size, ind );
   buf[ind++] = '"';

   /* terminate string */
   buf[ind] = '\0';

   /* convert to aterm */
   theString = ATparse( buf );

   /* free buffer */
   free( buf );
   
   /* return quotes string */
   return theString;
}
/* flex user code */
