#!/bin/sh

rm -f config.cache config.log acconfig.h aclocal.m4

autoxt
aclocal -I .
autoconf -f 
#--warnings=all
automake -a 
#--warnings=all  --warnings=no-portability

touch sig/*/*.str sig/*/*.c sig/*/*.rtree